version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm and yarn
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for the devcontainer
  # To get started with Dependabot version updates, you'll need to specify which
  # package ecosystems to update and where the package manifests are located.
  # Please see the documentation for more information:
  # https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
  # https://containers.dev/guide/dependabot
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
